// ====================================================================
// DEMO SCENARIOS - 3 transaction scenarios matching backend data
// ====================================================================

export const DEMO_SCENARIOS = [
  {
    id: 1,
    name: 'Normal Transaction',
    expected: 'GREEN - ALLOW',
    description: 'Nguyen Van An (whitelisted, 5 years) transfers $250 to Tran Minh Tuan. Low risk, routine.',
    riskLevel: 'green',
    icon: 'shield-checkmark',
    transaction: {
      transaction_id: 'TXN_DEMO_001',
      sender_id: 'ACC_001',
      sender_name: 'Nguyen Van An',
      sender_account_type: 'savings',
      receiver_id: 'ACC_002',
      receiver_name: 'Tran Minh Tuan',
      amount: 250.0,
      currency: 'USD',
      transaction_type: 'transfer',
      device_id: 'DEV_001',
      ip_address: '14.161.42.100',
      channel: 'mobile',
      location: 'Ho Chi Minh City',
      description: 'Chuyen tien an trua',
    },
  },
  {
    id: 2,
    name: 'Structuring Pattern',
    expected: 'YELLOW - INVESTIGATE',
    description: 'Tran Thi B (new 45 days, HIGH velocity) sends $950. Suspected structuring: many txns just under $1,000.',
    riskLevel: 'yellow',
    icon: 'warning',
    transaction: {
      transaction_id: 'TXN_DEMO_002',
      sender_id: 'ACC_007',
      sender_name: 'Tran Thi B',
      sender_account_type: 'checking',
      receiver_id: 'ACC_002',
      receiver_name: 'Tran Minh Tuan',
      amount: 950.0,
      currency: 'USD',
      transaction_type: 'transfer',
      device_id: 'DEV_002',
      ip_address: '113.190.88.50',
      channel: 'mobile',
      location: 'Da Nang',
      description: 'Payment',
    },
  },
  {
    id: 3,
    name: 'Money Laundering',
    expected: 'RED - BLOCK',
    description: 'Unknown Entity (15 days, KYC pending) sends $25,000 to BLACKLISTED account via Tor/VPN.',
    riskLevel: 'red',
    icon: 'close-circle',
    transaction: {
      transaction_id: 'TXN_DEMO_003',
      sender_id: 'ACC_050',
      sender_name: 'Unknown Entity',
      sender_account_type: 'business',
      receiver_id: 'ACC_666',
      receiver_name: 'Blocked Account',
      amount: 25000.0,
      currency: 'USD',
      transaction_type: 'transfer',
      device_id: 'DEV_UNKNOWN_001',
      ip_address: '185.220.101.42 (Tor Exit Node)',
      channel: 'web',
      location: 'Unknown (VPN)',
      merchant_id: 'MERCH_SHELL',
      description: 'Business payment',
    },
  },
];

// Pipeline flow steps
export const PIPELINE_STEPS = [
  { id: 'submit', label: 'Transaction Submitted', shortLabel: 'Submit', phase: 'input' },
  { id: 'phase1', label: 'Phase 1: Real-Time Screening', shortLabel: 'Screening', phase: 'phase1' },
  { id: 'routing', label: 'Risk Routing Decision', shortLabel: 'Routing', phase: 'phase1' },
  { id: 'planner', label: 'Planner Agent: Investigation Plan', shortLabel: 'Planner', phase: 'phase2' },
  { id: 'executor', label: 'Executor: Collect Evidence', shortLabel: 'Executor', phase: 'phase2' },
  { id: 'vision', label: 'Vision Agent: Analyze Patterns', shortLabel: 'Vision', phase: 'phase2' },
  { id: 'evaluate', label: 'Planner: Evaluate Evidence', shortLabel: 'Evaluate', phase: 'phase2' },
  { id: 'report', label: 'Report Agent: Generate Report', shortLabel: 'Report', phase: 'phase2' },
  { id: 'detective', label: 'Detective: Final Adjudication', shortLabel: 'Detective', phase: 'phase3' },
  { id: 'decision', label: 'Final Decision & Enforcement', shortLabel: 'Decision', phase: 'phase3' },
];
